language: bash
sudo: required
services: docker

install:
  - docker run -d --name=rb_db -e MYSQL_ROOT_PASSWORD='supersecretpassword' -e MYSQL_DATABASE='reviewboard' -v mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf:ro -v /var/lib/mysql mysql:5.7.13
  - docker run -d --name=memcache memcached:1.4.28

script:
  - sed -i "s/exec httpd -DFOREGROUND/exec httpd -t/g" entrypoint.sh
  - docker build -t rbtest .
  - docker run --name=reviewboard --link rb_db:dbserver --link memcache -p 80:80 -e DATABASE=mysql rbtest
