language: bash
sudo: required
services: docker

install:
  - git clone https://github.com/ovidiub13/reviewboard-docker ~/reviewboard-docker
  - docker pull mysql:5.7.13
  - docker run -d --name=rb_db -e MYSQL_ROOT_PASSWORD='supersecretpassword' -e MYSQL_DATABASE='reviewboard' -v mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf:ro -v /var/lib/mysql mysql:5.7.13

script:
  - docker build -t rbtest .
  - docker images
  - docker run -d --name=reviewboard -link rb_db:dbserver -p 80:80 -e DATABASE=mysql rbtest
  - docker ps
  - docker logs reviewboard
